- name: testing handlers
  hosts: win1.example.com
  gather_facts: false
  force_handlers: true
  vars:
    fail_it: "{{ g_fail_it | default(False) }}"
  tasks:
    - name: T1
      debug:
        msg: Task 1
      notify:
        - H3
      changed_when: true

    - name: T2
      debug:
        msg: Task 2
      notify:
        - my handler 2
        - H1
      changed_when: true
      failed_when: fail_it | bool

    - name: T3
      debug:
        msg: Task 3
      notify:
        - H1
      changed_when: true
  handlers:
    - name: H1
      debug:
        msg: Handler 1

    - name: my handler 2
      debug:
        msg: Handler 2

    - name: H3
      debug:
        msg: Handler 3