- name: testing
  hosts: windows
  gather_facts: false
  tasks:
    - name: T1
      win_shell: dir asdf
      when: ''"example.com" in inventory_hostname'
      #failed_when: false 
      ignore_errors: true
      changed_when: false
      register: sh_result

    - debug:
        var: sh_result
      when: >
        inventory_hostname == 'win1.example.com' or
        inventory_hostname in groups['dbservers']
    
    - name: T2
      debug:
        msg: Task 2
      when: animal is defined

    - name: T3
      debug:
        msg: Task 3