---
- name: test loops
  hosts: windows
  gather_facts: false
  vars:
    value1: 1 2 3
    my_list:
      - item one
      - item two
  tasks:
    - name: T1
      debug:
        msg: Item is {{ item }}
      loop:
        - "{{ value1 }}"
        - hello world
        - 123
      when: inventory_hostname == "win1.example.com"

    - name: T2
      debug:
        msg: Task 2 item is {{ item }}
      loop: "{{ my_list }}"

    - name: T3
      debug:
        msg: Name={{ item.name }} age={{ item.age }}
      loop:
        - name: one
          age: 10
        - name: two
          age: 20
        - name: three
          age: 30