- name: testing
  hosts: win1.example.com
  gather_facts: false
  vars_files:
    - vars/user_info
  tasks:
    - name: T1
      debug:
        msg:
          - user is {{ user }}
          - pass is {{ pass }}

    - name: T2
      debug:
        msg: Task 2

    - name: T3
      debug:
        msg: Task 3

