- name: testing
  hosts: win1.example.com
  gather_facts: false
  vars:
    debug_fail: true
    fail_fail: true
  tasks:
    - name: T1
      debug:
        msg: Task 1
      failed_when: debug_fail | bool

    - name: T2
      fail:
        msg: Task 2
      when: fail_fail | bool

    - name: T3
      debug:
        msg: Task 3