---
- name: testing command
  hosts: win1
  gather_facts: false
  tasks:
    - name: system info
      win_command: systeminfo.exe
      register: cmd_result

    - name: display the result of win_command
      debug:
        var: cmd_result.stdout_lines