---
- name: Testing Error Handling
  hosts: win1
  gather_facts: false
  tasks:
    - name: Task 1
      win_shell:  dir abc
      #failed_when: false
      ignore_errors: true
      register: sh_result

    - name: Task 2
      debug:
        var: sh_result
        
    - name: Task 3
      debug:
        msg: Task 3
...