- name: external task file
  hosts: win1.example.com
  tasks:
    - name: importing tasks
      vars:
        data: IMPORT
      import_tasks: tasks/external.yaml

    - name: including external tasks
      vars:
        data: "{{ item }}"
      include_tasks: tasks/external.yaml
      loop:
        - one
        - two
        - three

