- name: first dummy
  hosts: all
  tasks:
    - name: Task 1
      debug:
        msg: "Hello There :)"

    - name: Task 2
      win_ping:
      register: anyname
    
    - name: Result of task 2
      debug:
        var: anyname
