---
- name: Testing external Task file
  hosts: win1
  gather_facts: false
  tasks:
    - name: This is import
      import_tasks: tasks/external.yaml
      vars:
        item: CHEATING

    - name: Include
      include_tasks: tasks/external.yaml
      loop:
        - 1
        - 2
        - 3
        
    - name: Task 5
      debug:
        msg: Task 5
...