- name: testing magic variables
  hosts: windows
  tasks:
    - name: show magic variable
      debug:
        msg: 
          - my ip is {{ ansible_facts.interfaces[0].ipv4.address }}
          - win1 ip is {{ hostvars['win1.example.com']['ansible_facts']['interfaces'][0]['ipv4']['address'] }}
          - win2 ip is {{ hostvars['win2.example.com']['ansible_facts']['interfaces'][0]['ipv4']['address'] }}
