- name: Testing handlers
  hosts: windows
  gather_facts: false
  force_handlers: true
  tasks:
    - name: T1
      debug:
        msg: Task 1
      changed_when: true
      notify:
        - H3
        - H 2

    - name: T2
      debug:
        msg: Task 2
      changed_when: true
      failed_when: inventory_hostname == 'win1.example.com'
      notify:
        - H1

    - name: T3
      debug:
        msg: Task 3
      changed_when: true
      notify:
        - H 2

  handlers:
    - name: H1
      debug:
        msg: Handler 1

    - name: H 2
      debug:
        msg: Handler 2

    - name: H3
      debug:
        msg: Handler 3
