- name: testing conditions
  hosts: webservers
  tasks:
    - name: check user albert
      win_user:
        name: albert
        state: query
      register: user_result

    - name: run if user exists
      vars:
        data: 5
      debug:
        msg: albert exists in {{ ansible_facts.fqdn }}
      when: 
        - user_result.state == 'present'
        - data >= 5
        - value1 is defined

    - name: whoami
      win_command: whoami
      register: cmd_result
      change_when: false

    - name: are you devops?
      vars:
        abc:
          - one
          - two
          - three
        search_data: two
      debug:
        msg: you are devops
      when:
        - search_data in abc
        - "'devops' in cmd_result.stdout"
