---
- name: Testing tags
  hosts: win1
  gather_facts: false
  tasks:
    - name: Task 1
      debug:
        msg: Task 1
      tags:
        - prod
        - testing

    - name: Task 2
      debug:
        msg: Task 2
      tags:
        - testing
        
    - name: Task 3
      debug:
        msg: Task 3
      tags:
        - prod
        
...