---
- name: testing loops
  hosts: windows
  vars:
    user_list:
      - name: albert
        groups: Administrators
      - name: mike
        groups: Users
      - name: julie
        groups: Users
  tasks:
    - name: simple loop
      debug:
        msg: your item is {{ item }}
      loop:
        - one
        - second data
        - 123

    - name: create user 
      debug:
        msg: "{{ item['name'] }} belongs to the following groups: {{ item['groups'] }}"
      loop: "{{ user_list }}"
