---
- name: my first playbook
  hosts: all
  tasks:
    - name: Task 1
      win_copy:
        content: Hello World
        dest: 'C:/Users/devops/Desktop/dummy2.txt'

    - name: Get hostname
      win_command:
        cmd: hostname.exe
      changed_when: False
      register: cmd_result

    - name: display result
      debug:
        msg: >
          The command you ran was {{ cmd_result.cmd }}
          and output is {{ cmd_result['stdout'] }}
...
